-- Qualifying availability + supplemental form fields (officials_analysis schema).
-- Apply on the judging DB (schema officials_analysis present):
--   psql "$DATABASE_URL" -f activityAnalysis/migrations/007_official_qualifying_tables.sql

CREATE TABLE IF NOT EXISTS officials_analysis.official_qualifying_supplemental (
    official_id INTEGER NOT NULL,
    supplemental_json JSONB,
    ethics_hints_json JSONB,
    last_modified TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT official_qualifying_supplemental_pkey PRIMARY KEY (official_id),
    CONSTRAINT official_qualifying_supplemental_official_id_fkey
        FOREIGN KEY (official_id) REFERENCES officials_analysis.officials (id)
);

CREATE TABLE IF NOT EXISTS officials_analysis.official_qualifying_availability (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    official_id INTEGER NOT NULL,
    competition_key TEXT NOT NULL,
    availability TEXT NOT NULL,
    raw_availability TEXT,
    last_modified TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT official_qualifying_availability_official_id_fkey
        FOREIGN KEY (official_id) REFERENCES officials_analysis.officials (id),
    CONSTRAINT official_qualifying_availability_official_competition_key
        UNIQUE (official_id, competition_key)
);

CREATE INDEX IF NOT EXISTS official_qualifying_availability_official_id_idx
    ON officials_analysis.official_qualifying_availability (official_id);
