-- 2027-style qualifying availability: one JSON row per official, per-competition config + criteria.
-- Replaces 007 tables (official_qualifying_supplemental / official_qualifying_availability).
-- Apply: psql "$DATABASE_URL" -f activityAnalysis/migrations/008_qualifying_availability_form.sql

DROP TABLE IF EXISTS officials_analysis.official_qualifying_availability;
DROP TABLE IF EXISTS officials_analysis.official_qualifying_supplemental;

CREATE TABLE IF NOT EXISTS officials_analysis.qualifying_availability_form (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    source_filename TEXT,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS officials_analysis.qualifying_availability_competition (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id INTEGER NOT NULL,
    prompt_key TEXT NOT NULL,
    title TEXT,
    location TEXT,
    event_dates TEXT,
    season_year TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT qualifying_availability_competition_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.qualifying_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT qualifying_availability_competition_form_prompt_key
        UNIQUE (form_id, prompt_key)
);

CREATE INDEX IF NOT EXISTS qualifying_availability_competition_form_id_idx
    ON officials_analysis.qualifying_availability_competition (form_id);

-- Directory appointment type × discipline × optional level relevant to each form competition.
CREATE TABLE IF NOT EXISTS officials_analysis.qualifying_competition_criteria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competition_id INTEGER NOT NULL,
    appointment_type_id INTEGER NOT NULL,
    discipline_id INTEGER NOT NULL,
    level_id INTEGER,
    CONSTRAINT qualifying_competition_criteria_competition_id_fkey
        FOREIGN KEY (competition_id)
        REFERENCES officials_analysis.qualifying_availability_competition (id)
        ON DELETE CASCADE,
    CONSTRAINT qualifying_competition_criteria_appointment_type_id_fkey
        FOREIGN KEY (appointment_type_id)
        REFERENCES officials_analysis.appointment_types (id),
    CONSTRAINT qualifying_competition_criteria_discipline_id_fkey
        FOREIGN KEY (discipline_id)
        REFERENCES officials_analysis.disciplines (id),
    CONSTRAINT qualifying_competition_criteria_level_id_fkey
        FOREIGN KEY (level_id)
        REFERENCES officials_analysis.levels (id),
    CONSTRAINT qualifying_competition_criteria_unique
        UNIQUE NULLS NOT DISTINCT (competition_id, appointment_type_id, discipline_id, level_id)
);

CREATE INDEX IF NOT EXISTS qualifying_competition_criteria_competition_id_idx
    ON officials_analysis.qualifying_competition_criteria (competition_id);

-- Full form row per official (all columns, including per-competition answers).
CREATE TABLE IF NOT EXISTS officials_analysis.qualifying_official_form_response (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id INTEGER NOT NULL,
    official_id INTEGER NOT NULL,
    member_number TEXT,
    response_json JSONB NOT NULL,
    CONSTRAINT qualifying_official_form_response_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.qualifying_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT qualifying_official_form_response_official_id_fkey
        FOREIGN KEY (official_id)
        REFERENCES officials_analysis.officials (id),
    CONSTRAINT qualifying_official_form_response_form_official_unique
        UNIQUE (form_id, official_id)
);

CREATE INDEX IF NOT EXISTS qualifying_official_form_response_form_id_idx
    ON officials_analysis.qualifying_official_form_response (form_id);

-- Normalized availability for reporting (derived from response_json at load time).
CREATE TABLE IF NOT EXISTS officials_analysis.qualifying_official_competition_availability (
    form_id INTEGER NOT NULL,
    official_id INTEGER NOT NULL,
    competition_id INTEGER NOT NULL,
    availability_code TEXT NOT NULL,
    raw_value TEXT,
    CONSTRAINT qualifying_official_comp_avail_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.qualifying_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT qualifying_official_comp_avail_official_id_fkey
        FOREIGN KEY (official_id)
        REFERENCES officials_analysis.officials (id),
    CONSTRAINT qualifying_official_comp_avail_competition_id_fkey
        FOREIGN KEY (competition_id)
        REFERENCES officials_analysis.qualifying_availability_competition (id)
        ON DELETE CASCADE,
    CONSTRAINT qualifying_official_competition_availability_pkey
        PRIMARY KEY (form_id, official_id, competition_id)
);

CREATE INDEX IF NOT EXISTS qualifying_official_comp_avail_competition_id_idx
    ON officials_analysis.qualifying_official_competition_availability (competition_id);
