-- International judge availability form (Google Form export).
-- Apply: psql "$DATABASE_URL" -f activityAnalysis/migrations/041_international_availability_form.sql

CREATE TABLE IF NOT EXISTS officials_analysis.international_availability_form (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    source_filename TEXT,
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT international_availability_form_label_key UNIQUE (label)
);

CREATE TABLE IF NOT EXISTS officials_analysis.international_availability_event (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id INTEGER NOT NULL,
    prompt_key TEXT NOT NULL,
    short_label TEXT NOT NULL,
    column_kind TEXT NOT NULL DEFAULT 'event',
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT international_availability_event_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.international_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT international_availability_event_form_prompt_key
        UNIQUE (form_id, prompt_key),
    CONSTRAINT international_availability_event_column_kind_check
        CHECK (column_kind IN ('event', 'supplemental'))
);

CREATE INDEX IF NOT EXISTS international_availability_event_form_id_idx
    ON officials_analysis.international_availability_event (form_id);

CREATE TABLE IF NOT EXISTS officials_analysis.international_form_response (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id INTEGER NOT NULL,
    response_key TEXT NOT NULL,
    email TEXT,
    first_name TEXT,
    last_name TEXT,
    response_json JSONB NOT NULL,
    CONSTRAINT international_form_response_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.international_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT international_form_response_form_response_key
        UNIQUE (form_id, response_key)
);

CREATE INDEX IF NOT EXISTS international_form_response_form_id_idx
    ON officials_analysis.international_form_response (form_id);

CREATE TABLE IF NOT EXISTS officials_analysis.international_response_event_availability (
    form_id INTEGER NOT NULL,
    response_id INTEGER NOT NULL,
    event_id INTEGER NOT NULL,
    availability_code TEXT NOT NULL,
    raw_value TEXT,
    CONSTRAINT international_response_event_avail_form_id_fkey
        FOREIGN KEY (form_id)
        REFERENCES officials_analysis.international_availability_form (id)
        ON DELETE CASCADE,
    CONSTRAINT international_response_event_avail_response_id_fkey
        FOREIGN KEY (response_id)
        REFERENCES officials_analysis.international_form_response (id)
        ON DELETE CASCADE,
    CONSTRAINT international_response_event_avail_event_id_fkey
        FOREIGN KEY (event_id)
        REFERENCES officials_analysis.international_availability_event (id)
        ON DELETE CASCADE,
    CONSTRAINT international_response_event_availability_pkey
        PRIMARY KEY (form_id, response_id, event_id)
);

CREATE INDEX IF NOT EXISTS international_response_event_avail_event_id_idx
    ON officials_analysis.international_response_event_availability (event_id);
